-- WriteDB: Tabla de salas (maestro)
CREATE TABLE IF NOT EXISTS rooms (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 3) PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Insertar sala inicial (required por aplicación)
INSERT INTO rooms (id, name) VALUES (1, 'Sala 1'),(2,'Sala 2');

